steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build docker image
  args: ['build', '-t=${_GCR_DOCKER_IMAGE_PATH}:$COMMIT_SHA', '-t=${_GCR_DOCKER_IMAGE_PATH}:latest', '.']
  dir: ${_SERVICE_FOLDER_NAME}
- name: 'gcr.io/cloud-builders/docker'
  id: Push docker image with SHA tag
  args: ['push', '${_GCR_DOCKER_IMAGE_PATH}:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  id: Push docker image with latest tag
  args: ['push', '${_GCR_DOCKER_IMAGE_PATH}:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy on Google Cloud Run
  args: ['run', 'deploy', '${_CLOUD_RUN_SERVICE_NAME}', '--image=${_GCR_DOCKER_IMAGE_PATH}:$COMMIT_SHA', '--platform=${_PLATFORM}', '--region=${_RUN_REGION}', '--allow-unauthenticated', '--project=$PROJECT_ID', '--set-env-vars=PROJECTID=$PROJECT_ID, INSTANCE=${_SPANNER_ID}, DATABASE=${_SPANNER_DATABASE}, JWT_SECRET=${_JWT_SECRET}, EXPIRE_IN=${_EXPIRATION}']
options:
  substitution_option: 'ALLOW_LOOSE'

