version: 2
jobs:
  deploy_to_staging:
    docker:
      - image: google/cloud-sdk 
    environment:
      - PROJECT_NAME: "searce-academy"
      - GOOGLE_PROJECT_ID: "searce-academy"
      - WORKDIR: "omegatrade-app/backend/"
    steps:
      - checkout
      - run: 
          name: Setup Google Cloud SDK
          command: |
            apt-get install -qq -y gettext
            echo $GCLOUD_KEY_JSON > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - setup_remote_docker
      - run: 
          name: Docker build and push
          command: |
            gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
            echo ${WORKDIR}
            cd ${WORKDIR} && docker build -t gcr.io/searce-academy/omega-trade/dev/backend:${CIRCLE_SHA1} -f dockerfile.local.emulator .
            docker push gcr.io/searce-academy/omega-trade/dev/backend:${CIRCLE_SHA1}
      - run: 
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy omegatrade-backend-dev-ci \
            --region us-west1 \
            --image gcr.io/searce-academy/omega-trade/dev/backend \
            --platform managed \
            --allow-unauthenticated \
            --project searce-academy \
            --port 9020
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - deploy_to_staging:
          filters:
            branches:
              only: main
