jobs:
  build_and_deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - cloudrun/init
      - cloudrun/build:
          tag: 'gcr.io/searce-academy/omega-trade/dev/backend:${CIRCLE_SHA1}'
      - cloudrun/deploy:
          image: 'gcr.io/searce-academy/omega-trade/dev/backend:${CIRCLE_SHA1}'
          platform: managed
          region: us-east1
          service-name: omegatrade-backend-dev-ci
          unauthenticated: true
      - run:
          command: >
            GCP_API_RESULTS=$(curl -s "$GCP_DEPLOY_ENDPOINT")

            if [ "$GCP_API_RESULTS" != "Hello World!" ]; then
              echo "Result is unexpected"
              echo 'Result: '
              curl -s "$GCP_DEPLOY_ENDPOINT"
              exit 1;
            fi
          name: Test managed deployed service.
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.2
version: 2.1
workflows:
  build_and_deploy_to_managed_workflow:
    jobs:
      - build_and_deploy