FROM node:10.16.3
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . ./
RUN export SPANNER_EMULATOR_HOST=localhost:9010

CMD [ "npm", "start" ]

FROM gcr.io/cloud-spanner-emulator/emulator
