FROM gcr.io/cloud-spanner-emulator/emulator as emulator

FROM google/cloud-sdk
RUN gcloud config configurations create emulator \
  && gcloud config set auth/disable_credentials true \
  && gcloud config set project test-project \
  && gcloud config set api_endpoint_overrides/spanner https://multi-proc-cont-spanner-em-i3nfvlaq3a-uc.a.run.app/

FROM node:10.16.3
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . ./
RUN export SPANNER_EMULATOR_HOST=multi-proc-cont-spanner-em-i3nfvlaq3a-uc.a.run.app:9010
CMD [ "npm", "start" ]
